[profile.release]
strip = true
opt-level = "z"
lto = true
panic = "abort"
codegen-units = 1

[package]
name = "oblivion-admin-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = "0.26"
clap = { version = "4.4", features = ["derive"] }
libc = "0.2.172"

