[target.x86_64-unknown-linux-musl]
linker = "musl-gcc"
rustflags = [
  "-C", "target-feature=+crt-static",
  "-L", "openssl-3.5.0",
  "-l", "ssl",
  "-l", "crypto",
  "-l", "c",
  "-l", "dl",
  "-l", "m",
  "-l", "pthread"
]

